### PR TITLE
RELION 3.0/3.1 STAR handling bugfix

### PR DESCRIPTION
**Pull request by brisvag**
I accidentally changed the reading of relion3.0 to divide shifts by pixel size. This reverts it.

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]
good stuff! looks nice and clean. I would change the mode keys from `3.1` and `3.0` to `RELION 3.0` and `RELION 3.1` okay to merge as is!

**Comment by brisvag** [comment]
Or maybe even better, change from `mode` to `relion_version`? I think mode is still sort of a legacy of when I used to think dynamo tables were star files xD

**Comment by alisterburt** [comment]
Hahah - Warp and EMAN use STAR files too so let’s stick with mode!

**Comment by brisvag** [comment]
I see! then yes, I'll update like you suggested!

**Pull request merged**
